### ISSUE TITLE
it won't compile with Xcode 9.1

### ISSUE THREAD

**Issue by GINNOV** [pryomoax/SwiftSSDP#2]
| => swift build
Fetching https://github.com/pryomoax/SwiftAbstractLogger.git
Fetching https://github.com/nvzqz/Weak.git
Fetching https://github.com/robbiehanson/CocoaAsyncSocket.git
error: noManifest(baseURL: "https://github.com/robbiehanson/CocoaAsyncSocket.git", version: Optional("7.5.1"))

**Comment by kywix** [comment]
any progress in fixing this issue? Or a clue on what to look for a fix..

**Comment by redfearnk** [comment]
I too find that it does not compile with Xcode 9.1, but because of "Ambiguous use of operator !="

**Comment by pryomoax** [comment]
Sorry, I've not had time to update this project and get back into it. There's many improvements I'd like to make but don't have the capacity at present.

**Comment by GINNOV** [comment]
I was able to make it work for xcode 9 - the changes very very basic

**Comment by paulbatessonos** [comment]
@GINNOV I've officially updated the project to Swift 4/Xcode 9.2. Make sure to target `v0.5.1` to get the updates. Sorry it took so long.
