### ISSUE TITLE
can't discover some devices

### ISSUE THREAD

**Issue by GINNOV** [pryomoax/SwiftSSDP#4]
thank you for sharing this project - very helpful and well structured.
I can discover my Sonos in no time just like in your readme is documented, however with WEMO switches I don't even receive a callback after the M-SEARCH. Any clue on what could be the issue or where to look to resolve?

I know that you don't have time, I am just looking for clues and resolve on my own.
thz

**Comment by paulbatessonos** [comment]
Have you used other libraries to discover WEMO devices? Some device need UPnP to be enabled for SSDP. Also, ensure you are searching for devices/services as appropriate. You can try searching for all devices/services and see what comes back

**Comment by GINNOV** [comment]
I whipped up a node and python script to test if I was using the correct urn and way of finding the devices and yes indeed the switches are found. There's no swift library for wemo so I was hoping of using this one. 

ssdp:all just returns everything that I got on the network but wemo devices

**Comment by pryomoax** [comment]
I'm wondering if they get discarded due to missing information. You don't happen to have a capture of the SSDP headers for Wemo devices? Did you connect a logger to SwiftSSDP? You might see more information about discovery there?

I have node projects myself, but only one Wemo device for a timer. I can check if via SSDP + node I can see if and inspect myself.

**Comment by GINNOV** [comment]
oh I had not noticed the notification of your reply. Sorry.
Yes, I have attacehd the key three wemo definitions. 


[wemo.zip](https://github.com/pryomoax/SwiftSSDP/files/1778080/wemo.zip)

**Comment by pryomoax** [comment]
@GINNOV how are you constructing your search target? Looks like you should be using `Belkin` as the value for the `schema`.

**Comment by GINNOV** [comment]
Yes, I do.
My code matches yours.
I also enabled the logger to see everything that is trapped before it get parsed and I still don't see any Belkin device at all.

**Comment by rob-nash** [comment]
Try to avoid this guy 

https://github.com/rob-nash/Rotary/issues/1
